### ISSUE TITLE
BEM in realworld

### ISSUE THREAD

**Issue by ilyar** [bem/bem-react-core#100]
https://github.com/gothinkster/realworld

**Comment by awinogradov** [comment]
@ilyar explain your issue, please

**Comment by ilyar** [comment]
например форкнуть https://github.com/gothinkster/react-redux-realworld-example-app это реализация с применением React / Redux в рамках проекта TodoMVC for the RealWorld™ и заиспользовать в нем bem-react-core для демонстрации всей мощи БЭМ.

**Comment by awinogradov** [comment]
https://github.com/bem/bem-react-core/issues/49
