### ISSUE TITLE
`declMod` receives undefined instead of props 

### ISSUE THREAD

**Issue by Koreil** [bem/bem-react-core#117]
In some cases `declMod` receives `undefined` instead of `props` (empty Object), so it's causes TypeError.

**Comment by awinogradov** [comment]
@Koreil show some examples, please. It's difficult to understand without examples.

**Comment by veged** [comment]
@Koreil ping ;-)

**Comment by Koreil** [comment]
Sorry for the delay :)

I want to use `declMod` for link. So, I’m trying to do it like this: 

`export default declMod(({ linkMod }) => linkMod, { … })`

or like this:

`export default declMod({linkMod: true}, { … })`

Everything looks fine, but on keyboard focus suddenly causes TypeError:

`Uncaught TypeError: Cannot read property ‘linkMod’ of undefined`

**Comment by awinogradov** [comment]
Can you show code snippet where we can reproduce this error?

**Comment by zxqfox** [comment]
@awinogradov Just wanna repeat about some sandbox or online demo that can drastically simplify the process of reproduction errors of this kind.

**Comment by Koreil** [comment]
My apologies, a problem wasn't in `declMod`, I've made mistake while binding methods.
