### ISSUE TITLE
Make `addBemClassName` function for further redefinition

### ISSUE THREAD

**Issue by veged** [bem/bem-react-core#126]

**Comment by awinogradov** [comment]
@veged do you want to wrap this `mode`? Because now it's possible to override this `mode`, but it's static only.

**Comment by veged** [comment]
@awinogradov the point is to give ability of redefinition in `decl` — now (since this field just boolean) you can only completely redefine it, but for "smart" redefinition we need add it here https://github.com/bem/bem-react-core/blob/9139dd1ad185d13cdd0cd404901edd5a0b83262d/src/Core.js#L27
