### ISSUE TITLE
Support bem-config in client js by env variables

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#133]
Change this https://github.com/bem/bem-react-core/blob/master/src/index.js#L10 to 

``` js
__dangerouslySetNaming : process.env.bemConfig.naming
```

It relates to https://webpack.js.org/plugins/environment-plugin/

**Comment by awinogradov** [comment]
@tadatuta it's ok?)

**Comment by alexbaumgertner** [comment]
Should we mock `process.env.bemConfig` in browser?

**Comment by awinogradov** [comment]
@alexbaumgertner what do you mean? It'll be passed by the webpack plugin and will work fine.

**Comment by alexbaumgertner** [comment]
Client-side css class naming:
![](https://user-images.githubusercontent.com/223620/29793210-bcb7d388-8c4b-11e7-88ab-5da390cb1c5c.png)

**Comment by awinogradov** [comment]
@alexbaumgertner make a question please

**Comment by alexbaumgertner** [comment]
@awinogradov 
React render HTML in runtime. How can I configure naming?

React naming scheme (bundled in `bem-react-core` and non configurable for now)
```html
 <span class="Button-Text"></span>
```

I need origin
```html
<span class="Button__Text"></span>
```

**Comment by awinogradov** [comment]
I explained this answer here https://github.com/bem-site/bem-forum-content-ru/issues/1413#issuecomment-326408147. It's ok before we close this issue.

**Comment by deeonis** [comment]
correct link: https://github.com/bem-sdk-archive/bem-config/issues/20#issuecomment-312430632
