### ISSUE TITLE
error with bem-react-core@0.4.3

### ISSUE THREAD

**Issue by Guria** [bem/bem-react-core#134]
> ./node_modules/bem-react-core/dist/index.js
> Module not found: Can't resolve './SimpleComponent' in '/home/ubuntu/workspace/node_modules/bem-react-core/dist'

0.4.2 was working but 0.4.3 gives me above error. Haven't tried to debug yet, so no more details at the moment.

**Comment by Guria** [comment]
Seems some problem with filename case. For some reason SimpleComponent is published as `./dist/simpleComponent.js`. Have no idea how i happened, since source file named correctly.

**Comment by Guria** [comment]
probably it was published from case insensitive file system, where it was originally created with first small letter. So now it must be republished with cleaning `dist` before.
cc @veged

**Comment by veged** [comment]
so strange, but you are right — republish 0.4.4
