### ISSUE TITLE
Problems with 0.4.3-4

### ISSUE THREAD

**Issue by nasyrov** [bem/bem-react-core#137]
Hi guys,

Cheers up for an awesome package!

There are some problems with the package 0.4.3-4 versions:

- For 0.4.3 it tries to require `simpleComponent` instead of `SimpleComponent`;
- For 0.4.4 there is no `dist` folder.

Could you please have a look?

Cheers,
E

**Comment by Yeti-or** [comment]
Thanks we have already found problem with 0.4.4 https://github.com/bem/bem-react-core/issues/136
And you are right 0.4.3 has really strange bug: in src we have `SimpleComponent` but in published package we have different name of file: `simpleComponent`

**Comment by veged** [comment]
should be ok now — try v0.4.6 pls
