### ISSUE TITLE
elemMods should works as usual

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-react-core#156]
I saw https://github.com/bem/bem-react-core/pull/135

Still think that this should works:
```jsx
mix={{
    block: 'foo’,
    elem: 'bar’, 
    elemMods: {mod: 'val’}
}}
```
Because we have some kind of standard of bemjson: https://en.bem.info/platform/bemjson/#conventions-for-standard-bemjson-modes

Thank you!

**Comment by Yeti-or** [comment]
dublicate of https://github.com/bem/bem-react-core/issues/130
