### ISSUE TITLE
Support nested mixes 

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#16]
if `instance.buildClassName` exec else build by b

**Comment by veged** [comment]
after discussion with @dfilatov and @narqo we figured  out that `<MyBlock mix={<OtherBlock/>}/>` can't provide any instance with `buildClassName` and most probably we need custom renderer here for return needed parts of instance

**Comment by veged** [comment]
let's wait http://isfiberreadyyet.com to implement custom renderer
