### ISSUE TITLE
Use Error Boundaries for Bem

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#164]
This line https://github.com/bem/bem-react-core/blob/master/src/Bem.js#L15 throw warning if `this.context` undefined. It's possible for root elements.

![image](https://user-images.githubusercontent.com/982072/32985909-91c0f76a-ccd6-11e7-8791-dcfd5ee24dae.png)

**Comment by Yeti-or** [comment]
@awinogradov push today's branch

**Comment by awinogradov** [comment]
https://github.com/bem/bem-react-core/pull/174
