### ISSUE TITLE
Find a way to write specs without fixtures

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-react-core#185]
> We really need a way to describe decls right here. We SHOULD NOT test babel-import plugin or webpack-bem-loader here to resolve 'b:*' dependencies and it's better to put declarations right in test files (and remove fixtures folder) for readability purposes.

For now we have files with specs and fixtures. Also we need babel-bem-import plugin to resolve these files and call applyDecls.
There should be a way to do it manually without getting chocked out.

Something like:
```js
const { decl, bake } = require('..'); // bem-react-core

it('should check some', () => {
  const BakedButton = bake(
    decl({ block: 'button', method1() {} }),
    decl({ block: 'button', method1(...args) { return this.base(...args); } }),
    declMod({ block: 'button', mod: 'disabled', method1() { return false; } })
  );
});
```
instead of writing 3 files with decls, using babel-plugin-bem-import with levels and import in spec file 
```js
import * as BakedButton from 'b:button';
import * as BakedButtonDisabled from 'b:button m:disabled';
```

**Comment by awinogradov** [comment]
So, looks good, but how you want to reuse decls between specs?

**Comment by zxqfox** [comment]
I don't.
If I do I will move them to usual CommonJS modules.

But I don't.

**Comment by awinogradov** [comment]
Relates to #189
