### ISSUE TITLE
Clone simple objects in modes

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-react-core#196]
Feels like we can use Object.assign or Object.create if possible

Like:
```js
decl({
  block: 'any',
  attrs: {} // vs attrs() { return {} }
})
```

cc @awinogradov

**Comment by veged** [comment]
we also need to be sure that there is only one level nesting in `attrs`

**Comment by awinogradov** [comment]
Solved in v2 https://github.com/bem/bem-react-core/pull/238
