### ISSUE TITLE
Add example with different naming for several levels

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-react-core#199]

**Comment by veged** [comment]
actually we already have such example in tests:
  - https://github.com/bem/bem-react-core/blob/master/.bemrc.js
  - https://github.com/bem/bem-react-core/blob/23473d34951c9121e7bae04eda8a8c7306c65194/tests/bemClassName.spec.js#L18
  - https://github.com/bem/bem-react-core/blob/2abefb58173019c63c9ae9e379669b3aa066d7b9/tests/fixtures3.blocks/another-naming-block__elem.js#L5

**Comment by awinogradov** [comment]
brc@2 doesn't support dynamic redefinition levels. Naming can be changed for any component or for base Block and Elem.
