### ISSUE TITLE
Add parents mods in inheritance

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#206]
If we want to get `Button` modifiers inherited from `Control`, we need to add:
``` js
decl(Control, {
  block: 'Button',
  mods() {
    return this.__base(...arguments); // <- this
  }
})
```

**Comment by veged** [comment]
may be it's not a bug, but ability to inherit without pulling modifiers from parent — so we need more real usage examples here to decide the solution...

**Comment by awinogradov** [comment]
Ok, it's a part of API. We should explain it in docs for 1.0.0
