### ISSUE TITLE
`displayName` static field is ignored

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-react-core#207]
```js
const React = require('react');
const { decl } = require('bem-react-core');

const Icon = (decl({
  block: 'icon'
}, {
  displayName: 'definitely-not-icon'
})).applyDecls();

const icon = React.createElement(Icon, {});
icon.type.displayName; // "icon", but expected "definitely-not-icon"
```

It's a regression
https://runkit.com/embed/guop94nbnjj3

This works fine in the latest stable version (0.4.6).

**Comment by veged** [comment]
is it really needed to do? we have `block`/`elem` fields and infer `displayName` from them — so "semantically" `displayName` is read-only field

is there any real cases where we need such possibility? for now I consider any tossing with `displayName` as hacks

**Comment by zxqfox** [comment]
Yes17:10, 19 января 2018 г., Sergey Berezhnoy <notifications@github.com>:is it really needed to do? we have block/elem fields and infer displayName from them — so "semantically" displayName is read-only field
is there any real cases where we need such possibility? for now I consider any tossing with displayName as hacks

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by veged** [comment]
@zxqfox expand your answer pls ;-) could you provide details about any real cases where we need such possibility?

**Comment by zxqfox** [comment]
```js
decl({
  'block': 'Button'
}, {
  propTypes: {
    icon: PropTypes.object
  }
});

decl({
  block: 'Icon'
}, {
  isIcon(x) {
    return x && x.type && x.type.displayName === 'Icon';
    // Not my code, actually, but we have users who use this.
  }
});

decl(Icon, {
  block: 'CustomIcon'
}, {
  displayName: 'Icon'
});

// At user level:
import { Button, Icon, CustomIcon } from 'super-library';

class ES6Icon extends Icon {
  static displayName = 'Icon';
};

<Button icon={<ES6Icon />}>Guess it works</Button>
<Button icon={<CustomIcon />}>Definitely does not work ;-(</Button>
```

Is it enough?

**Comment by veged** [comment]
@zxqfox there is a better way for this particular case... let's discuss offline for more details

**Comment by awinogradov** [comment]
Let's discuss in complex problems here #231
