### ISSUE TITLE
Bem block ref prop

### ISSUE THREAD

**Issue by gulalex181** [bem/bem-react-core#217]
It seems doesn't work:
`<Bem block='Block' ref={(...) => {...}}>...</Bem>`
I get a Bem component instance instead of a div DOM-element.

**Comment by veged** [comment]
@gulalex181 could you please provide a code example? (cause after https://github.com/bem/bem-react-core/pull/163/files it should be ok)

**Comment by awinogradov** [comment]
It's valid behavior for React component. Look at this example https://jsfiddle.net/pj9v8qa7/
