### ISSUE TITLE
Move to CDN

### ISSUE THREAD

**Issue by Vittly** [bem/bem-react-core#218]
Request of [this](https://reactjs.org/docs/cdn-links.html). Why did we miss it ?

**Comment by denisbalyko** [comment]
May be you need this: https://unpkg.com/bem-react-core ?

**Comment by Vittly** [comment]
mmm, okey. So does everyone know about it and we have no need to move it to yastatic or write about it in readme ?

**Comment by denisbalyko** [comment]
It seems this should go into the 1.0.0 documentation, но это не точно:)
Original issue https://github.com/bem/bem-react-core/issues/96#issuecomment-351719814
сс @awinogradov

**Comment by Vittly** [comment]
Also if I add `<script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>` to my page I get `window.React` variable and `externals: { react: 'React' }` in my webpack-config works well. But if I add `npkg.com/bem-react-core` on page I only get error `exports` in undefined. How can I fix it?

**Comment by rifler** [comment]
try `https://unpkg.com/bem-react-core@1.0.0-rc.8/umd/react.js`, maybe it helps (но это не точно)

**Comment by Vittly** [comment]
Eh! This works:

```html
<script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script src="https://unpkg.com/prop-types/prop-types.min.js"></script>
<script src="https://unpkg.com/bem-react-core@1.0.0-rc.8/umd/react.js"></script>
```

Let's add it to Readme and we can close the issue

**Comment by awinogradov** [comment]
@Vittly make a PR ;)

**Comment by veged** [comment]
@innabelaya please add to README in "usage" section
```html
<script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
<script src="https://unpkg.com/prop-types/prop-types.min.js"></script>
<script src="https://unpkg.com/bem-react-core@1.0.0-rc.8/umd/react.js"></script>
```
