### ISSUE TITLE
PropTypes dependency

### ISSUE THREAD

**Issue by Vittly** [bem/bem-react-core#219]
I think it is missed. I cant build without it

**Comment by awinogradov** [comment]
it's peerDependency

**Comment by Vittly** [comment]
from what peer?

**Comment by awinogradov** [comment]
https://github.com/bem/bem-react-core/blob/master/package.json#L88-L94

**Comment by Vittly** [comment]
moved to https://github.com/bem/bem-react-core/issues/225
