### ISSUE TITLE
Implement mods methods

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#22]
setMod, getMod, delMod, getMods, toggleMod

**Comment by dfilatov** [comment]
o_O We don't have explicit mods anymore, by now mods are used for setting css only and they are extracted fom state and props.

**Comment by veged** [comment]
@awinogradov could you provide more usage examples, so we can introduce alternatives that's fit "new way" more

**Comment by awinogradov** [comment]
I'm agree. It's not needed here.
