### ISSUE TITLE
PropType of a modifier affect the block's one

### ISSUE THREAD

**Issue by remnev** [bem/bem-react-core#220]
Look at the example below:

components/content/content.react.js
```javascript
import Block from 'b:block m:foo=bar';

export default decl({
   block: 'content',
   content() {
       return [
           <Block key="pure" />, // note here, we use the block without a modifier, and it causes a warning
           <Block key="with-mod" foo="bar" prop={1} />
       ];
   }
});
```
components/block/block.react.js
```javascript
// a pure block doesn't have PropTypes at all
export default decl({
   block: 'block',
   content({children}) {
       return <b>{children}</b>;
   }
});
```
components/block/_foo/block_foo_bar.react.js
```javascript
import PropTypes from 'prop-types';

export default declMod({foo: 'bar'}, {
   block: 'block',
   content({prop}) {
       return <i>{prop}</i>;
   }
}, {
   propTypes: {
       prop: PropTypes.number.isRequired
   }
});
```
Do you agree, that propTypes of a modifier **should not** affect propTypes of its base block?

**Comment by deeonis** [comment]
@veged @Yeti-or @awinogradov здесь такая же история. Запланируйте asap plz https://nda.ya.ru/3U4Mew

**Comment by Yeti-or** [comment]
we will investigate this issue as soon as possible

**Comment by veged** [comment]
that's because of `propTypes` is static field and affect all instances — so since modifiers are runtime props we have no any obvious solution here :-(

**Comment by remnev** [comment]
Guys, unbelievable...

There is no way to use modifiers while this **bug** exists.

It has to be solved. Or you should get rid of the propTypes static property at all. Because it doesn't  work.

Why I am so upset. Every component in my project had a propTypes declaration, the linter checks this. But when I used modifiers for the first time – everything broke down. Now the linter rule is disabled. Some components have propTypes declaration, some – have not. I lost consistency of the component declaration. I lost control of prop types in components, which have modifiers.

**Comment by veged** [comment]
@remnev not sure that I'm understand what exactly breaks when you start to use modifiers — could you please provide code example?

**Comment by veged** [comment]
Yeah, I know the examples of impossible things with current implementation :-(

But what you suggest do to in situations like this:
```js
// in another special case, the table cell prints received data as different structure
declMod({mod2: 'val2'}, {
    block: 'table',
    elem: 'td',
    content({data}) { ... }
}, {
    propTypes: {
        data: PropTypes.shape({
            f1: PropTypes.string,
            f2: PropTypes.string
        })
    }
})
```

There is still a problem with clashing of things declared for modifiers. So maybe it's better just understand it and avoid clashing in declarations for modifiers?

**Comment by remnev** [comment]
It would be perfect, if it worked like a `mods()`, `attrs()`, etc methods. I mean it's up to you to rewrite entire value, or call `__base` and enrich the result. Thus in such cases, props won't affect each other.


BTW, another example, which I faced recently.
```js
delc({
    block: 'foo',
    content({foo, bar}) {
        return foo + bar;
    }
}, {
    propTypes: {
        foo: PropTypes.string.isRequired,
        bar: PropTypes.string.isRequired
    }
});

// while data is loading, this modifier works
// it doesn't use props at all, but causes the problem because of base block propTypes
delcMod({loading: true}, {
    block: 'foo',
    content() {
        return 'Loading...';
    }
});
```

**Comment by Yeti-or** [comment]
Maybe we should move propTypes to an instance method, not a static field?
It would be: `getPropTypes()`, `getDefaultProps()`

**Comment by awinogradov** [comment]
Let's discuss in complex problems here #231
