### ISSUE TITLE
Huge rework proposal

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-react-core#223]
For now our entrance level is very high for a typical React-developer.
Dependency from inheritance makes our code even more harder to read.
Loader is required and magically converts source code that makes it impossible to use with static analyse tools.
I believe we should remove a lot of custom logic to be closer to common practices and tools to reuse them. E.g. things for TypeScript, or even Babel with Flow which is popular in React community.

Issues like these: https://github.com/bem/bem-react-core/issues/186, https://github.com/bem/bem-react-core/issues/207 and https://github.com/bem/bem-react-core/issues/220 tells us that we should at least try to get back to the beginning and try to rewrite it from scratch according to real life requirements and current specs and probably some tests.

I guess would be enough if:
- Source code of components will be based on ES6 classes with more familiar
- TS support and tooling (webstorm, vscode) for components. Guess it means dropping inherit dependency
- Drop mapping of React lifecycle hooks because there is no logical reason to do it
- Ability to applyDecls without using internal storage. Feels like it means importing components with different modifiers will produce different classes.

To get it real we should make a lot more tests for core functionality and try to write absolutely new code from scratch but use current tests.

Here is a nice try: https://github.com/yarastqt/react-bem-next
We can continue this work and merge it to the `bem-react-core` as 2.0.

**Comment by awinogradov** [comment]
We had a conversation with @yarastqt and I offered to move specs from here to `bem-react-next`. It's really nice attempt ;)

**Comment by awinogradov** [comment]
Solved in v2 https://github.com/bem/bem-react-core/pull/238
