### ISSUE TITLE
Boolean modifier with false value in block modifier generates extra junk markup

### ISSUE THREAD

**Issue by gulalex181** [bem/bem-react-core#224]
```
b:Block

mods () {
  return {
    someValue: false,
  }
}
```
generates
`<div class="Block"></div>`
and that's ok, but if property with false value appears in modifier then we have junk markup:
```
b:Block m:Mod

mods () {
  return {
    someAnotherValue: false,
  }
}

<div class="Block Block"></div>

**Comment by rifler** [comment]
I fix similar bug in https://github.com/bem/bem-react-core/issues/203
Maybe this issue fixed too
But there was no release with my fixes on npm

**Comment by awinogradov** [comment]
It'll be released soon ;)
