### ISSUE TITLE
Merge state between levels

### ISSUE THREAD

**Issue by joshuan** [bem/bem-react-core#234]
common.blocks:
``` js
decl({
   block: 'App',
   state: { a: 'a' },
   content: () {
     return <pre>{JSON.strigify(this.state)}</pre>;
   }
})
```

desktop.blocks: 
``` js
decl({
   block: 'App',
   state: { b: 'b' }
})
```

I want to render starting, gets
`{ "a": "a", "b": "b" } `

If I'm going to point a state in `willInit`, then I should always remember that the state could be listed above and write `this.state = { ...this.state, b: 'b' };`, and it seems not the most convenient way and a potential place for an error.

**Comment by awinogradov** [comment]
Solved in v2 https://github.com/bem/bem-react-core/pull/238
