### ISSUE TITLE
Removing propTypes at production

### ISSUE THREAD

**Issue by Vittly** [bem/bem-react-core#235]
Folks using `class MyComponent extends React.Component { ... }`/`MyComponent.propTypes = ...` can remove "propTypes" with [babel-plugin-transform-react-remove-prop-types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) or [babel-plugin-remove-proptypes](https://www.npmjs.com/package/babel-plugin-remove-proptypes). Any of this doesn't work with `decl(... { propTypes: ... } ...)` or `declMod(... { propTypes: ... } ...)`.

Where can we put this code:

```js
module.exports = ({ types: t }) => ({
    visitor: {
        CallExpression: path => {
            const callee = path.node.callee;
            const args = path.node.arguments;

            if (t.isIdentifier(callee, { name: 'decl' }) || t.isIdentifier(callee, { name: 'declMod' })) {
                let stat = args[args.length - 1];

                // connect() can be last arg
                if (t.isCallExpression(stat) && t.isIdentifier(stat.callee, { name: 'connect' })) {
                    stat = args[args.length - 2];
                }

                if (t.isObjectExpression(stat) && stat.properties.length <= 2) {
                    // is it static part?
                    if (stat.properties.some(prop => t.isObjectMethod(prop))) return;

                    const propTypesIndex = stat.properties.findIndex(prop =>
                        t.isObjectProperty(prop) &&
                        t.isIdentifier(prop.key, { name: 'propTypes' })
                    );

                    if (propTypesIndex >= 0) {
                        // removing propTypes
                        stat.properties.splice(propTypesIndex, 1);
                    }
                }
            }
        }
    }
});
```

Do we need new "bem/babel-plugin-remove-proptypes-from-bem-react-core" ?
Can we put it somewhere in "bem-react-core"?

**Comment by awinogradov** [comment]
I think the better way is using standalone plugin.

**Comment by awinogradov** [comment]
ping @Vittly

**Comment by Vittly** [comment]
I want more opinions. Please @zxqfox @Yeti-or don't stay apart

**Comment by awinogradov** [comment]
@Vittly we had a discussion about this offline. Don't worry ;)

**Comment by Yeti-or** [comment]
With v2.0.0  https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types works, but with comment annotation
check this issue for more information: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/99

we could add opts to this plugin or (less desirable) fork it

**Comment by awinogradov** [comment]
It's not actual for v2
