### ISSUE TITLE
Cannot use external preact from CDN

### ISSUE THREAD

**Issue by Vittly** [bem/bem-react-core#239]
CDN way to use "preact" is https://cdn.jsdelivr.net/npm/preact/dist/preact.min.js. This script adds global variable `preact`. "bem-react-core" [references "preact" via *Preact* global variable](https://github.com/bem/bem-react-core/blob/20a5825cefe7aab3cdeeb05d2f232e7c35629876/config/rollup.config.preact.js#L18). Variables are different and we got error.

**Comment by awinogradov** [comment]
@Vittly looks like we can safely accept PR from you ;)

**Comment by awinogradov** [comment]
No suppurt for Preact
