### ISSUE TITLE
Wrong version of package at cdn

### ISSUE THREAD

**Issue by Vittly** [bem/bem-react-core#240]
Readme [has link to CDN](https://github.com/bem/bem-react-core/blob/master/docs/en/README.md#cdn).

We have several problems with it:
1. React/PropTypes are optional. Someone can use Preact without PropTypes. Can we keep only "bem-react-core" link? Also I think we have to suggest few links for react, preact, etc.
2. "bem-react-core" link references some old version. Latest version is "1.0.0-rc.10" and CDN has version "1.0.0-rc.8". Can we  replace it with "latest" or "production"? Other suggestions?

**Comment by awinogradov** [comment]
1. The links provided in README are separated, you can use any combination of them. Everybody can use `bem-react-core` without `prop-types`. List of the links is not a recommendation.
2. Our principal position does not use URL with variative content. But if you want to use that links you can always to do it by https://unpkg.com API. For ex.: https://unpkg.com/bem-react-core@latest/umd/react.js

**Comment by Vittly** [comment]
Hmm. So what about current link in README?
