### ISSUE TITLE
Passing easy-bem-naming as values for cls prop is broken in v2

### ISSUE THREAD

**Issue by DarthVictor** [bem/bem-react-core#242]
Hi, we use [easy-bem-naming](https://github.com/awinogradov/easy-bem-naming) for bem class names in our project and passing them as cls prop used to work well in v1. In v2 bem-react-core ignores such props. At the same time it works if we pass string instead of an object.
So works well
```
import bem from 'easy-bem-naming';
const b = () => bem()('menu');
....
cls={'' + b().e('menu')}
```
and 
```
cls={b().e('menu')}
```
is broken.

It seems that we problem is here:
https://github.com/bem/bem-react-core/blob/master/src/Bem.js#L123

Changing body to smth like
```
if(entity.entity) return entity + '';
return typeof entity === 'string' ? entity : entityClassName(entity);
```
fixes the issue

Also may be fixed here
https://github.com/bem/bem-sdk/blob/master/packages/naming.entity.stringify/index.js#L12

**Comment by yarastqt** [comment]
This bug in the first version, second version not yet ready :)
