### ISSUE TITLE
[improvement] Add Redux support

### ISSUE THREAD

**Issue by andreevWork** [bem/bem-react-core#248]
Предлагаю добавить поддержку Redux, а точнее react-redux под капот bem-react-core, чтобы не использовать в проектах Provider и connect.

Сейчас в версии 0.4.2 это работает так:
```
export default decl({
    block: 'Popup',

    content({ children }) {
        return children;
    }
},
null,
connect(
    ({ popup }) => ({ popup })
));

```

И в данном варианте у меня часто возникает такой кейс, что я хочу определить скажем common блок, ему нужны некие данные из redux store,  а дальше на уровнях touch и desktop мне нужны еще данные, но у каждого уровня свои и хотелось бы иметь возможность "мерджить" "деревья" redux store. Покажу на абстрактном пример о чем я:
```
common.popup.js

export default decl({
    block: 'Popup',

    // ...Component code
},
null,
// Можно через статичные свойства, или другим способом, это не принципиально 
{
    mapStateToProps(state) {
       return { popup: state.popup };
    }
});

-------------------

desktop.popup.js

export default decl({
    block: 'Popup'

    // ...Component code
},
null,
{
    mapStateToProps(state) {
       return { another: state.another };
    }
});

```
Соответственно в блоке на уровне desktop в ```this.props``` буде два поддерева ```popup```
и ```another```

Я не предлагаю делать такую поддержку "из коробки", а например с помощью отдельного модуля и его последующего подключения, чтобы проекты которым не нужен Redux не тащили ничего лишнего:
 ```
import "bem-react-core/redux-support" // Типо того
```

Возможно вообще сделать некую систему плагинов, и сделать плагин под редакс.

В любом случае хочется послушать, что другие разработчики и мэйнтейнеры об этом думают, Спасибо.

**Comment by awinogradov** [comment]
Привет! Спасибо тебе за ишью! Прости, что так долго, мы тут готовили релиз v2. Может ты заглянешь в доку снова и потребность в таком хелпере отпадет? Если нет, то давай обсуждать уже на уровне v2.

**Comment by andreevWork** [comment]
Ничего страшного за поздний ответ, вижу вы явно были заняты v2.
Кстати я посмотрел новое апи, и в нем также можно добавить, то что я бы хотел видеть, покажу уже на примере v2:

есть блок, ему нужные некие данные из store:
```
class TabsBase extends Block {
    static propsFromState = state => ({ tabsState: state.tabsState }) 

    или вообще дать возможность декларировать какие поддеревья тебе нужны (но конечно вариант с функцией остается)
    static propsFromState = ['tabsState']

    block = 'Tabs';

    mods() {
        return {
            withStat: this.props.withStat
        };
    }

    ...other code
}
```

и скажем модификатор:
```
class TabsWithStat extends Block {
    static propsFromState = ['statState', 'anotherState.specialProp']

    block = 'Tabs';

    ...other code
}

const Tabs = withMods(TabsBase, TabsWithStat);
```

В итоге - разработчик пишет различные модификаторы или делает extends от любого блока, и в каждом случае в самом конце мы получаем компонент, который имеет всего один ```connect``` в нем смерджены все поддеревья из статичных свойств ```propsFromState```, тоже соответственно и для actions
 
На мой взгляд это сильно упростит код, тем кто работает с Redux, возможно кого-то убедит заюзать redux вместо других решений.

Также если честно, я не знаю красивого метода "из коробки" наследовать и мерджить данные в контексте react-redux, кроме чьих-то велосипедов.

И также хочу еще раз отметить, я не прощу чтобы ядро bem-react-core знало про некий redux-connect и прочее, хочется сделать что-то типо расширений или плагинов, и первым плагином сделать то, о чем написал выше. Что думаете? Спасибо

**Comment by awinogradov** [comment]
Если я все правильно понял, ты хочешь сэкономить на коннектах. Но почему? Если такое делать модулем/плагином, то чем это будет отличаться от connect? Единственное что я в лоб вижу, это бросать в контекст весь стейт, а-ля Provider на уровне рута. И вытаскивать то что надо для компонента, опираясь на статический метод. Но это значит, что каждый компонент ты все ровно будешь заворачивать в HOC. Потому что в противном случае, компоненты будут грязными и переиспользовать их будет не так удобно как хотелось бы. А если придётся таки заворачивать в HOC, то чем это будет отличаться от connect?

**Comment by awinogradov** [comment]
Поддержать мерж в наследовании допустим не так сложно. А вот что делать с описанным выше я сходу не знаю.

**Comment by andreevWork** [comment]
Понял о чем ты, действительно во 2 версии сделать как я предлагаю не покатит.

В принципе, если сделать мердж статичных свойств, и написать небольшую обертку на react-redux connect чтобы он брал инфу из этих статичных свойств, то будет уже, гораздо лучше чем есть, а экспортить будем и stateless и statefull версию, и от stateless можно делать extends, типо такого:
```
export class Tabs extends Block { // Для наследований или использования без redux
    static propTypes = {
         tabsState: PropTypes.shape({ ... }).isRequired
    };

    static propsFromState = ['tabsState'];

    block = 'Tabs';

    mods() {
        return {
            withStat: this.props.withStat
        };
    }

    ...other code
}

export const TabsConnected = connectBlock(Tabs); // Законекченная версия
```

```connectBlock``` я смогу и сам реализовать, а вот мердж конечно только через вас.

Вообще хотелось бы увидеть некий объект Config - который позволяет настроить всякие моменты, типо separator в нейминге классов, и что напрямую относится к этой задаче, возможность добавить массив ключей, а ключи это статичные свойства классов, которые будут мерджится при наследовании:
```
import { Config } from 'bem-react-core';

Config.staticFieldsToMerge = ['propsFromState', 'actionsFromState'];
```

Что думаете? Спасибо

**Comment by yarastqt** [comment]
Кажется, что `static propsFromState = ['tabsState']` не самый удачный вариант API для redux, т.к. очень часто бывает, что тебе нужно описать какие-то селекторы для доступа\мемоизации. Так же на мой взгляд не очень хорошо иметь в UI компоненте подключение к стору и описание диспатчеров\селекторов, лучше выносить это на какой-то отдельный уровень `containers|pages|connectors`.

**Comment by andreevWork** [comment]
1. По поводу ```static propsFromState = ['tabsState']``` это просто вариант когда нужно все поддерево, я полностью согласен что функцию нужно оставить, выше я просто предложил массив между делом, не в нем суть.

2. А вот про UI компоненты два момента
* во-первых не всех утраивает тема с контейнерами, и писать каждый раз обертку когда ты хочешь что-то достать из redux

* во-вторых, что более важно, мое предложение выше никак не обязывает вас писать все в UI-stateless компонентах, можно спокойно написать те же statefull-контейнеры через вышеописанный способ

В этом весь прикол, вам просто дается более удобный способ работы со store, а как эту работу организовать на уровне приложения, контейнеры/неконтейнеры, это уже вопрос индивидуальный для каждой команды.

**Comment by awinogradov** [comment]
Вопрос: как ты с помощью статического объекта хотел разрулить мапинг стейта в пропсы?

Например, вот такой https://github.com/reduxjs/redux/blob/master/examples/todomvc/src/containers/MainSection.js#L8-L11

**Comment by awinogradov** [comment]
Сходу мого предложить вот такое решие. Можно пофантазировать, но смысл, кажется, понятен.

``` js
// lib/withMods.js
import { withMods } from 'bem-react-core';

export function customWithMods(res = [], K, ...mods) {
   mods.forEach(mod => {
      // Тут способ мержа может быть любой, в зависимости от типа и задачи
      res = [].concat(res, mods.propsFromState);
   });

  return withMods(K, ...mods);
}

// components/Button_theme_normal.js
import { Button } from './Button';

export class ButtonThemeNormal extends Button {
   static mod = () => true;
   static propsFromState = ['oneMore']
}

// components/Button.js
import { Block } from 'bem-react-core';

export class Button extends Block {
   block = 'Button';
   static propsFromState = ['tabsState']
}

// index.js
import { customWithMods } from '../lib/withMods';
import { Button } from './components/Button';
import { ButtonThemeNormal } from './components/Button_theme_normal';

let propsFromState = [];

const Component = customWithMods(propsFromState, Button, ButtonThemeNormal);
const Connected = connect(propsFromState)(Component);
```

**Comment by awinogradov** [comment]
@andreevWork ping

**Comment by andreevWork** [comment]
Сорри я походу все еще мыслю в контексте 1 brc, закрою тогда issue вопросов нет.
