### ISSUE TITLE
Implement bem: false

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#25]
It shouldn't generate className

**Comment by dfilatov** [comment]
What for?

**Comment by awinogradov** [comment]
For preventing class generation

**Comment by dfilatov** [comment]
Please, show sensible case

**Comment by awinogradov** [comment]
``` js
decl({
  block: 'block',
  elem: 'js',
  tag: 'script' // 'style', 
})
```

**Comment by dfilatov** [comment]
I'm confused with bem:false (wtf?!?) for this, I'd prefer something like className:false

**Comment by awinogradov** [comment]
@dfilatov yeah, why not. I wrote bem:false as an example because it the same idea in bem-xjst
