### ISSUE TITLE
Миксование блоков

### ISSUE THREAD

**Issue by KIlyaA** [bem/bem-react-core#258]
Хотел бы удобный API для миксования, сейчас миксы можно определять только внутри компонентов. Но это очень не удобно т.к появляется сильная зависимость от какого либо блока.
```
class Button extends Block {
    block = 'Button';
    mix() {
        return {
            block: 'Header',
            elem: 'Button'
        }
    }
}
```

Хотелось бы выставлять микс в родительском компоненте:
```
class Header extends Block {
    block = 'Header';
    
    content() {
        return (
            <Bem block="Header" elem="Title">Title</Bem>
            <Button mix={{ block: 'Header', elem: 'Button' }}>Button</Button>
        );
    }
}
```

**Comment by yarastqt** [comment]
Мы специально убрали возможность передавать `mix` в компонент который наследует `Block/Elem`, чтобы иметь единственную точку расширения — `className`, у каждого блока сейчас присудствует API для формирования класса, ты бы мог сделать это так:
```js
class Header extends Block {
    block = 'Header';
    
    content() {
        return (
            <Bem block="Header" elem="Title">Title</Bem>
            <Button className={this.bemClassName('Button')}>Button</Button>
        );
    }
}
```

Пока что это API не задокументировано (возможно в будущем немного изменится название)
