### ISSUE TITLE
Order of files in case of block importing self modifier

### ISSUE THREAD

**Issue by artems** [bem/bem-react-core#26]
Допустим у меня есть блок `button`.
Внутри я использую модификатор, который должен быть подключен всегда вместе с `button`. Например `button_disable_yes`.

Если я напишу в файле `button.js`
```js
import Button from "b:button m:disable=yes";
```
То файл `button_disable_yes.js` подключится раньше `button.js`. Получится что `button` переопределяет `button_disable_yes`, а не наоборот.

**Comment by veged** [comment]
только писать в файле `button.js`
```js
import Button from "b:button m:disable=yes";
```
нет смысла (`Button` не нужен) — нужно писать:
```js
import "m:disable=yes";
```

**Comment by veged** [comment]
мы добавили тест и оказалось, что оно уже работает как надо — декларации модификаторов всегда применяются после декларации самой сущности
