### ISSUE TITLE
Аналог PureComponent

### ISSUE THREAD

**Issue by KIlyaA** [bem/bem-react-core#260]
Если ли аналог PureComponent или какие-то практики его реализовать?

**Comment by yarastqt** [comment]
Привет, пока что нет, компоненты `Block` и `Elem` наследуют `Component`, ты можешь сам пока описать `SCU` и использовать `shallowequal` для проверки. В будущем я думал про то чтобы добавить `PureBlock` и `PureElem` но пока не добрались. Компонент `Bem` наследует `PureComponent`, что кажется логично для такого компонента.
