### ISSUE TITLE
Отпилить зависимость, использующие console.assert

### ISSUE THREAD

**Issue by jabzzy** [bem/bem-react-core#262]
- console.assert не везде поддерживается
- использется, например, в `@bem/sdk.naming.entity.stringify` внутри `stringifyWrapper`

**Comment by jabzzy** [comment]
cc @awinogradov

**Comment by yarastqt** [comment]
Нужно просто внутри `@bem/sdk.naming.entity.stringify` использовать `assert` библиотеку. Но как временное решение, можно просто убрать пока что этот `console.assert`, кажется, что он не особо там нужен.
