### ISSUE TITLE
Remove instanceof guard

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#264]
https://github.com/bem/bem-react-core/blob/5fa258e13488ac5a883dfb51e6780bb7bac02438/packages/react/src/index.ts#L523-L525

It doesn't work for extended components.

**Comment by yarastqt** [comment]
Have an example?

This code works fine:
```js
class Block {}
class ButtonCommon extends Block {}
class ButtonDesktop extends ButtonCommon {}

ButtonDesktop.prototype instanceof Block
```

**Comment by alexmog2** [comment]
if you have
```class ButtonThemeNormal extends ButtonCommon```
you won't be able to create a mix of `(ButtonDesktop, ButtonThemeNormal)`
