### ISSUE TITLE
Pass blockName for Bem component by context

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#269]
Now we need write `<Bem block="B" elem="E" />` everywhere, it's not ok.

**Comment by yarastqt** [comment]
It seems that it should work

Block:
https://github.com/bem/bem-react-core/blob/5fa258e13488ac5a883dfb51e6780bb7bac02438/packages/react/src/index.ts#L196-L204

Elem:
https://github.com/bem/bem-react-core/blob/5fa258e13488ac5a883dfb51e6780bb7bac02438/packages/react/src/index.ts#L494-L499

**Comment by awinogradov** [comment]
Yep, we need release
