### ISSUE TITLE
Naming presets should be configured in one place

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#27]
We can use presets instead of custom params for bem-naming and b_. List: canonical, harry-roberts, modern(current by default).

``` js
...
bemLoader: {
  naming: 'harry-roberts',
  levels: [...]
}
...
```

**Comment by awinogradov** [comment]
bem-naming support them https://github.com/bem-sdk/bem-naming/tree/master/lib/presets

**Comment by veged** [comment]
it can be done with Babel plugin which can provide `bem-config` module with concrete naming options
