### ISSUE TITLE
Get block and elem from constructor name

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#270]
Problems:
- uglify

Passing `elem`:
- `block` from context, because element can't be out of block
- `elem` from constructor name

**Comment by yarastqt** [comment]
Now its fork

Block
https://github.com/bem/bem-react-core/blob/5fa258e13488ac5a883dfb51e6780bb7bac02438/packages/react/src/index.ts#L278-L280

Elem
https://github.com/bem/bem-react-core/blob/5fa258e13488ac5a883dfb51e6780bb7bac02438/packages/react/src/index.ts#L450-L452

**Comment by awinogradov** [comment]
If it works we need to have some specs for that case and change base classes from abstract to real.
