### ISSUE TITLE
Support HMR

### ISSUE THREAD

**Issue by iniel** [bem/bem-react-core#28]
Full reload needed :(

**Comment by awinogradov** [comment]
I think it's doesn't work because we can't match React-component to the JS on the fs. It's impossible now ;( But we need to try)

**Comment by vkhv** [comment]
+1

**Comment by veged** [comment]
@awinogradov is it still undone? looks like now everything reloaded as hot as never before ;-)

**Comment by awinogradov** [comment]
@veged it works on the project's level with some manipulations in code. So, I can write the example with that manipulations and close this issue. Ok?

**Comment by veged** [comment]
@awinogradov sure! just after example ;-)

**Comment by awinogradov** [comment]
Ok, if you want HMR you need to to write smth like this https://github.com/react-boilerplate/react-boilerplate/blob/master/app/app.js#L82-L90, but you need use full path to BEM-entity instead of BEM-import notation. And... It'll work ;)
