### ISSUE TITLE
Class extending Block can't be an Elem

### ISSUE THREAD

**Issue by alexmog2** [bem/bem-react-core#280]
With current class hierarchy, classes extending from Block can't be elems in other classes. For example:

```
class Control extends Block {...}
class Menu extends Control {
    block = 'menu';
}
class MenuItem extends Control {
    block = 'menu';
    elem = 'item';
}
```

Here `elem='item'` will have no effect (because Block doesn't have `elem` property). As a workaround, `getClassNameParams` can be overridden with a copy from `Elem`, then it generates proper class names. However it is still not really an `Elem` then...

To avoid this kind of conflict, `Elem` should either not be a separate class, or have most of its code in `Block`

**Comment by awinogradov** [comment]
So, we talk a little about it. And made a decision: you don't need to extends Elem from Block. Try to use HOC instead.
