### ISSUE TITLE
Bem should be a class

### ISSUE THREAD

**Issue by alexmog2** [bem/bem-react-core#281]
Making it a stateless component creates issues. You can't override anything on it (for example stringify). Having to use forwardRef makes it unnecessary complicated too.

**Comment by awinogradov** [comment]
It's already class

https://github.com/bem/bem-react-core/blob/master/packages/react/src/index.ts#L175-L178

**Comment by awinogradov** [comment]
Ref forwarding PR https://github.com/bem/bem-react-core/pull/276
