### ISSUE TITLE
Add helper for most common cases of `declMod`

### ISSUE THREAD

**Issue by veged** [bem/bem-react-core#48]
- `declMod({ modName : ‘modVal’ }, …)` — for declaration of _modName_modVal with automatically adding of `props.modName` to `mods`
  - `declMod({ modName : ‘*’ }, …)` — for common declaration for any value of `modName` (and auto adding to `mods`)
  - `declMod({ modName : ({ modName }) => ... })` — for declaration additional custom matching for `modName` (and auto adding to `mods`)
  - current `declMod(({ modName }) => …, { mods() { … } })` — for completely manual control of modifiers

**Comment by zxqfox** [comment]
- `declMod({ modName : ‘*’ }, …)` — for common declaration for any value of modName (and auto adding to mods)

For any value of any modifier? Isn't it the same as block or elem itself?

**Comment by dfilatov** [comment]
> For any value of any modifier?

No, for any value of modifier with name equals to `modName`

**Comment by zxqfox** [comment]
I hope `*` here is only a wildcard and not a real value ;-D
