### ISSUE TITLE
More useful examples

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#49]
- examples
  - [redux](https://github.com/awinogradov/bem-react-stub/tree/redux) - ready to move
     - package.json
  - real-world
     - package.json
  - universal
     - package.json

[Many examples](https://github.com/reactjs/redux/tree/master/examples) to port.

**Comment by iniel** [comment]
It would be great to see example of block like https://github.com/reactjs/redux/blob/master/examples/real-world/src/containers/App.js

**Comment by awinogradov** [comment]
[Example](https://gist.github.com/awinogradov/e8f9ea51a9c44b6cc0ae911e3851c2ea) for connection entity to state.

**Comment by veged** [comment]
use `create-bem-react-app`

**Comment by awinogradov** [comment]
https://github.com/awinogradov/create-bem-react-app

**Comment by awinogradov** [comment]
#170
