### ISSUE TITLE
Make code examples in README.md more illustrative

### ISSUE THREAD

**Issue by andrew--r** [bem/bem-react-core#73]
In my opinion, existing code examples are too formal. `MyBlock_myMod1_myVal1` isn't very illustrative and related to real world use cases. What about making those examples more developer-friendly? We could use examples such as `Button`, `Input` or something like that instead of abstract `MyBlock`.

**Comment by awinogradov** [comment]
@andrew--r we'll try to do this in the nearest future. Thanks! Now you can find examples with real components [here](https://github.com/bem/bem-react-components)

**Comment by andrew--r** [comment]
@awinogradov I could send PR, if you don't mind

**Comment by awinogradov** [comment]
Cool! 🔥

**Comment by andrew--r** [comment]
@awinogradov here is it: #76
