### ISSUE TITLE
Add `style` handler

### ISSUE THREAD

**Issue by veged** [bem/bem-react-core#75]
Or, at least, make proper extend of `style` in `attrs`.

**Comment by awinogradov** [comment]
@veged what do you want? Maybe this proposal?

``` js
export default decl({
  block: 'MyStyledBlock',
  attrs: {
    id: 'block-id'
  },
  style({ color }) {
    return {
      color,
      width: '100px'
    };
  },
  content() {
    return 'My styled content';
  }
});
```

**Comment by veged** [comment]
@awinogradov yeah, something like this — current problem that `style` configured through `attrs` and has problems with merge on redefinitions
