### ISSUE TITLE
Ability to keep elem files in the same folder as block

### ISSUE THREAD

**Issue by kovchiy** [bem/bem-react-core#91]
This:
```
App/
  App.js
  Footer/
    App-Footer.js
```

Became this:
```
App/
  App.js
  App-Footer.js
```

And maybe the same for mods?
```
App/
  App.js
  App-Footer.js
  App-Footer_context_native.js
  App-Footer_context_browser.js
```

Please.

**Comment by tadatuta** [comment]
Should be easy to support as `bem-fs-scheme` is already used in https://github.com/bem/webpack-bem-loader so all we need to do is to provide an option.

**Comment by awinogradov** [comment]
Also, we can support:
```
- Block
  - Elem1.js
  - ShitElem.js
  - Block.js
```

**Comment by kovchiy** [comment]
also would be great

**Comment by zxqfox** [comment]
@awinogradov I don't see how you can detect elems without a special character:
```
Block/
  Shittyfile.js
  Anothershittyfile.js
  More.js
  AndMoreShittyFiles.js
```

**Comment by awinogradov** [comment]
@zxqfox all of them are elements

**Comment by awinogradov** [comment]
Do it here https://github.com/bem/webpack-bem-loader/issues/35 and https://github.com/bem/babel-plugin-bem-import/issues/20
