### ISSUE TITLE
Autobinding component methods

### ISSUE THREAD

**Issue by kovchiy** [bem/bem-react-core#92]
Here is my often situation:

```
export default decl({
    block: 'Doc',
    willInit (props) {
        this.onItemActivated = this.onItemActivated.bind(this)
        this.getDoctypeAndExamples = this.getDoctypeAndExamples.bind(this)
    }
    ...
```

Even in your examples I saw the same code.

Dont know about pros – I see a lot of cons. Could you fix this? Or maybe there is a strong explanation why I should not want to do this?

**Comment by awinogradov** [comment]
It is React API. It's necessary to save the context of the component instance. U can use unstable decorator for this https://github.com/andreypopp/autobind-decorator.
